"""
WriterAgent — the third and final agent in the sequential pipeline.

Reads both {raw_research} and {analysis} from session state via
template injection. Produces a polished Markdown research report
and calls save_report to persist it to disk. Uses gemini-2.5-pro
for higher quality prose in the final output.
"""

from google.adk.agents import LlmAgent
from ..tools.file_tool import save_report

GEMINI_PRO = "gemini-2.5-pro"  # Higher quality for the final written output

writer_agent = LlmAgent(
    name="WriterAgent",
    model=GEMINI_PRO,
    description=(
        "Professional technical writer that produces polished, structured "
        "Markdown research reports from analysis and raw findings."
    ),
    instruction="""
You are a Professional Technical Writer specialising in research reports.

You have been provided with:

=== RAW RESEARCH ===
{raw_research}
===================

=== ANALYSIS ===
{analysis}
===============

Using BOTH inputs above, write a complete, professional Markdown report.
Then call save_report(content=<full_report>, topic=<short_topic_name>)
to save it to disk.

Your report MUST contain ALL of these sections in this exact order:

# <Topic Title> — Research Report
*Generated by Multi-Agent AI Research Assistant (Google ADK + Gemini)*
*Date: <today's date>*

---

## Executive Summary
<2-3 sentences capturing the single most important finding and its significance>

---

## Key Findings

### 1. <Finding title from insight 1>
<Full paragraph expanding on this insight with context and implications>

### 2. <Finding title from insight 2>
<Full paragraph>

### 3. <Finding title from insight 3>
<Full paragraph>

### 4. <Finding title from insight 4>
<Full paragraph>

### 5. <Finding title from insight 5>
<Full paragraph>

---

## Data & Statistics

| Metric | Value | Source |
|--------|-------|--------|
| <metric> | <value> | [<domain>](<url>) |
(one row per statistic from the analysis)

---

## Analysis & Implications
<Paragraph 1: What the combined findings reveal about the topic>
<Paragraph 2: Practical implications for businesses, individuals, or the field>
<Paragraph 3: Expected trends or developments based on the evidence>

---

## Confidence & Limitations
- **Overall confidence**: <High/Medium/Low from analysis>
- **Source coverage**: <number> sources researched
- **Information gaps**: <gaps from analysis>
- **Suggested follow-up**: <what additional research would strengthen this>

---

## Conclusion
<3-4 sentences: summary of the most important insight, its significance,
and one clear recommendation or takeaway for the reader>

---

## Sources
<Numbered list of all URLs cited throughout the report>

---
*This report was autonomously generated by a 3-agent pipeline:*
*ResearcherAgent → AnalystAgent → WriterAgent*
*Powered by Google ADK and Gemini*
""",
    tools=[save_report],
    output_key="final_report",  # Saved to session.state["final_report"]
)
